baseURL = 'https://tschoenfelder.de/'
languageCode = 'en-us'
title = 'WIP'
theme = 'gokarna'

enableRobotsTXT = true

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url =  '/about/'
        weight =  1
    [[menu.main]]
        identifier = "blog"
        name = 'Blog'
        url =  '/blog/'
        weight =  2
    [[menu.main]]
        identifier = "contact"
        name = 'Contact'
        url = '/contact/'
        weight = 3
    [[menu.main]]
        identifier = "github"
        url = "https://github.com/Toterich"
        weight = 4

        # We use feather-icons: https://feathericons.com/
        pre = "<span data-feather='github'></span>"